### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by Megadash452** [Aliics/ezcli#9]
Hi, I'm interested in using this crate as a dependency in my project, but the recent version with the syntax that looks like something from the command line is not published to crates.io. I find it much simpler to use this other syntax rather than the one from the published version in crates.io. And I noticed that the github autobuild failed to publish the new version. Is there something I can help with to get it published?

**Comment by Aliics** [comment]
@Megadash452 Sorry about that. I don't really maintain this project much, but if I find the time I can patch the build to get this onto crates.io.

Maybe I'll find some time on the weekend.

**Comment by Aliics** [comment]
@Megadash452 I felt like tinkering with this and fixing a few things up before getting it back up on crates.io.
This should be good now. Hopefully it serves you well. :)
